name: mehmani
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  path_provider: ^2.0.11
  animated_bottom_navigation_bar: ^1.4.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  flutter_svg: ^2.2.0
  flutter_localizations:
    sdk: flutter
  motion_toast: ^2.1.8
  persian_number_utility: ^1.1.2
  get: ^4.6.5
  file_picker: ^10.3.2
  permission_handler: ^12.0.1
  # share: ^2.0.4
  restart_app: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.1.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir_m.ttf
    - family: niseBusch
      fonts:
        - asset: assets/fonts/nisebusch.ttf

    - family: nunito
      fonts:
        - asset: assets/fonts/nunito_bold.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
